---
deployment:
  tasks:
    - export DEPLOYPATH=/home/omahbarokah/
#    - /bin/cp -r * $DEPLOYPATH #copy all from root
    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/dev
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/dev/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/dev/css  